/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "uniqueid_constants.h"

namespace uniqueid {

const uniqueidConstants g_uniqueid_constants;

uniqueidConstants::uniqueidConstants() {
}

} // namespace

