/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef uniqueid_CONSTANTS_H
#define uniqueid_CONSTANTS_H

#include "uniqueid_types.h"

namespace uniqueid {

class uniqueidConstants {
 public:
  uniqueidConstants();

};

extern const uniqueidConstants g_uniqueid_constants;

} // namespace

#endif
